"use client";

import { useEffect, useMemo, useState } from "react";
import TMDBCollection from "./components/tmdb-collection";

type Movie = { id:number; title:string; year:number; rating:number; genres:string[]; symbol:string; palette:string; synopsis:string; };
type CuratedPosterMap = Record<number, string | null>;
const MOVIES: Movie[] = [
{id:1,title:"Interstellar",year:2014,rating:8.7,genres:["Sci-Fi","Drama","Adventure"],symbol:"✦",palette:"linear-gradient(145deg,#23364f,#6c4b67 48%,#e6a46d)",synopsis:"A team of explorers travels beyond this galaxy to discover whether mankind has a future among the stars."},
{id:2,title:"Dune: Part Two",year:2024,rating:8.5,genres:["Sci-Fi","Adventure","Drama"],symbol:"☼",palette:"linear-gradient(145deg,#171b30,#a55d3d 58%,#e9c38d)",synopsis:"Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family."},
{id:3,title:"The Dark Knight",year:2008,rating:9.0,genres:["Action","Crime","Drama"],symbol:"♜",palette:"linear-gradient(145deg,#171c2a,#424b58 55%,#a67c65)",synopsis:"Batman faces his greatest psychological and moral challenge when the Joker unleashes chaos on Gotham."},
{id:4,title:"Spider-Man: Across the Spider-Verse",year:2023,rating:8.6,genres:["Animation","Action","Adventure"],symbol:"◉",palette:"linear-gradient(145deg,#30235b,#d43c68 55%,#f4b75b)",synopsis:"Miles Morales catapults across the multiverse and encounters a team of Spider-People protecting its existence."},
{id:5,title:"Everything Everywhere All at Once",year:2022,rating:7.8,genres:["Sci-Fi","Action","Comedy"],symbol:"✺",palette:"linear-gradient(145deg,#31265c,#9c4f91 52%,#f2c66d)",synopsis:"An exhausted laundromat owner becomes the unlikely hero who must connect with versions of herself across the multiverse."},
{id:6,title:"The Shawshank Redemption",year:1994,rating:9.3,genres:["Drama"],symbol:"⌁",palette:"linear-gradient(145deg,#273e42,#78908a 55%,#d1b38b)",synopsis:"Two imprisoned men bond over years, finding solace and redemption through small acts of hope."},
{id:7,title:"Inception",year:2010,rating:8.8,genres:["Sci-Fi","Action","Thriller"],symbol:"◈",palette:"linear-gradient(145deg,#101d2d,#416477 54%,#d2a477)",synopsis:"A skilled thief who steals secrets through dream-sharing technology is offered a chance to erase his criminal past."},
{id:8,title:"Whiplash",year:2014,rating:8.5,genres:["Drama","Music"],symbol:"♫",palette:"linear-gradient(145deg,#211a20,#8c342f 56%,#df9c63)",synopsis:"A young drummer enters a conservatory where a ruthless instructor pushes him toward the edge of greatness."},
{id:9,title:"Parasite",year:2019,rating:8.5,genres:["Thriller","Drama","Comedy"],symbol:"⌂",palette:"linear-gradient(145deg,#243c32,#66816b 54%,#d5c39a)",synopsis:"A poor family insinuates itself into the life of a wealthy household, setting off a chain of unexpected events."},
{id:10,title:"Your Name",year:2016,rating:8.4,genres:["Animation","Romance","Drama"],symbol:"☄",palette:"linear-gradient(145deg,#33366e,#6a8dc6 50%,#f2a9a6)",synopsis:"Two teenagers mysteriously begin swapping bodies and form a connection that crosses time and distance."},
{id:11,title:"The Matrix",year:1999,rating:8.7,genres:["Sci-Fi","Action"],symbol:"⌘",palette:"linear-gradient(145deg,#071c18,#12634b 52%,#8cc99a)",synopsis:"A hacker discovers the unsettling truth about reality and joins a rebellion against the machines controlling humanity."},
{id:12,title:"La La Land",year:2016,rating:8.0,genres:["Romance","Drama","Music"],symbol:"♫",palette:"linear-gradient(145deg,#24275e,#d05c80 55%,#f5bd6e)",synopsis:"A jazz musician and an aspiring actor fall in love while pursuing their dreams in Los Angeles."},
{id:13,title:"Get Out",year:2017,rating:7.8,genres:["Horror","Thriller","Mystery"],symbol:"◉",palette:"linear-gradient(145deg,#152d28,#6a8b75 55%,#d4d0ad)",synopsis:"A weekend visit to meet his girlfriend's family turns into a disturbing discovery for a young photographer."},
{id:14,title:"Mad Max: Fury Road",year:2015,rating:8.1,genres:["Action","Adventure","Sci-Fi"],symbol:"⚡",palette:"linear-gradient(145deg,#5d291c,#d76b35 55%,#f5d16c)",synopsis:"In a post-apocalyptic wasteland, a road warrior helps a rebel escape a tyrant across the desert."},
{id:15,title:"Knives Out",year:2019,rating:7.9,genres:["Mystery","Comedy","Crime"],symbol:"✦",palette:"linear-gradient(145deg,#173b38,#517f71 55%,#d3bd8c)",synopsis:"A detective investigates the death of a celebrated crime novelist amid a family full of suspects."},
{id:16,title:"Coco",year:2017,rating:8.4,genres:["Animation","Family","Adventure"],symbol:"✿",palette:"linear-gradient(145deg,#49265b,#d25a5e 52%,#f2c568)",synopsis:"A music-loving boy enters the Land of the Dead to uncover his family's history and follow his dream."},
{id:17,title:"The Grand Budapest Hotel",year:2014,rating:8.1,genres:["Comedy","Adventure","Crime"],symbol:"▤",palette:"linear-gradient(145deg,#5d244c,#d46e91 53%,#f0c98b)",synopsis:"A legendary concierge and his young protégé become entangled in a theft and a family inheritance battle."},
{id:18,title:"A Quiet Place",year:2018,rating:7.5,genres:["Horror","Drama","Sci-Fi"],symbol:"◌",palette:"linear-gradient(145deg,#1c3027,#66785a 55%,#c6b48a)",synopsis:"A family survives in silence while hiding from creatures that hunt by sound."},
{id:19,title:"The Social Network",year:2010,rating:7.8,genres:["Drama","Biography"],symbol:"⌘",palette:"linear-gradient(145deg,#16213c,#405b83 55%,#a7b5c8)",synopsis:"The rise of a college social network sparks lawsuits and fractures friendships among its founders."},
{id:20,title:"Avengers: Endgame",year:2019,rating:8.4,genres:["Action","Adventure","Sci-Fi"],symbol:"✧",palette:"linear-gradient(145deg,#25213d,#78514f 55%,#e0b878)",synopsis:"After devastating losses, the remaining Avengers assemble for one final mission to restore the universe."},
{id:21,title:"Spirited Away",year:2001,rating:8.6,genres:["Animation","Fantasy","Adventure"],symbol:"☁",palette:"linear-gradient(145deg,#173c47,#4d8c92 55%,#f1c88c)",synopsis:"A young girl enters a world ruled by spirits and must find courage to rescue her transformed parents."},
{id:22,title:"Joker",year:2019,rating:8.4,genres:["Crime","Drama","Thriller"],symbol:"♠",palette:"linear-gradient(145deg,#24232d,#6c6d59 55%,#c6a47a)",synopsis:"A struggling comedian descends into madness as society's indifference pushes him toward a darker identity."},
{id:23,title:"The Conjuring",year:2013,rating:7.5,genres:["Horror","Mystery","Thriller"],symbol:"✧",palette:"linear-gradient(145deg,#151d2b,#46505e 55%,#b7a18b)",synopsis:"Paranormal investigators help a family terrorized by a dark presence in their farmhouse."},
{id:24,title:"Pride & Prejudice",year:2005,rating:7.8,genres:["Romance","Drama"],symbol:"❀",palette:"linear-gradient(145deg,#273c32,#82947b 55%,#e5cda4)",synopsis:"Elizabeth Bennet navigates manners, family expectations and her complicated feelings for Mr. Darcy."}
];
const GENRES = ["All","Action","Adventure","Animation","Comedy","Crime","Drama","Fantasy","Horror","Mystery","Romance","Sci-Fi","Thriller"];
type View = "Discover" | "Top Rated" | "For You" | "Watchlist";

export default function Home() {
 const [query,setQuery]=useState(""); const [genre,setGenre]=useState("All"); const [view,setView]=useState<View>("Discover"); const [selected,setSelected]=useState<Movie|null>(null); const [history,setHistory]=useState<number[]>([]); const [watchlist,setWatchlist]=useState<number[]>([]); const [ready,setReady]=useState(false); const [posters,setPosters]=useState<CuratedPosterMap>({});
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("cs-history")||"[]"));setWatchlist(JSON.parse(localStorage.getItem("cs-watchlist")||"[]"));}catch{}setReady(true); fetch("/api/curated-posters").then(r=>r.ok?r.json():Promise.reject(new Error("Poster lookup failed"))).then(data=>setPosters(data.posters||{})).catch(()=>setPosters({}));},[]);
 const movies=useMemo(()=>{let list=[...MOVIES];const q=query.trim().toLowerCase();if(q)list=list.filter(m=>(m.title+" "+m.genres.join(" ")).toLowerCase().includes(q));if(genre!=="All")list=list.filter(m=>m.genres.includes(genre));if(view==="Top Rated")list.sort((a,b)=>b.rating-a.rating);if(view==="For You"){const seen=history.map(id=>MOVIES.find(m=>m.id===id)).filter(Boolean) as Movie[];list=list.filter(m=>!history.includes(m.id));if(seen.length){const fav=seen.flatMap(m=>m.genres);list.sort((a,b)=>b.genres.filter(g=>fav.includes(g)).length-a.genres.filter(g=>fav.includes(g)).length||b.rating-a.rating)}else list.sort((a,b)=>b.rating-a.rating)}if(view==="Watchlist")list=list.filter(m=>watchlist.includes(m.id));return list;},[query,genre,view,history,watchlist]);
 function openMovie(m:Movie){setSelected(m);const next=[m.id,...history.filter(id=>id!==m.id)].slice(0,30);setHistory(next);try{localStorage.setItem("cs-history",JSON.stringify(next))}catch{}}
 function toggleWatch(id:number){const next=watchlist.includes(id)?watchlist.filter(x=>x!==id):[id,...watchlist];setWatchlist(next);try{localStorage.setItem("cs-watchlist",JSON.stringify(next))}catch{}}
 const activeLabel=view==="For You"?(history.length?"Picked from your viewing history":"Popular picks to get you started"):view==="Top Rated"?"Audience favourites, sorted by rating":view==="Watchlist"?"Films you saved for later":"A hand-picked starting point for your next movie night";
 return <main><header className="shell topbar"><div className="brand"><div className="brand-mark">▶</div><div>Cine<span>Sphere</span></div></div><nav className="nav"><a href="#discover">Discover</a><a href="#discover" onClick={()=>setView("Top Rated")}>Top rated</a><a href="#discover" onClick={()=>setView("For You")}>For you</a></nav><div className="status"><i/> Smart discovery <span style={{color:"#777f90"}}> · </span>{ready?"Ready":"Loading"}</div></header>
 <section className="shell hero"><div><div className="eyebrow">✦ YOUR NEXT GREAT WATCH STARTS HERE</div><h1>Less scrolling.<br/><em>More cinema.</em></h1><p>Discover films that stay with you. Explore crowd favourites, filter by genre, and build a watchlist shaped around what you love.</p><form className="searchbar" onSubmit={e=>{e.preventDefault();setView("Discover");document.getElementById("discover")?.scrollIntoView({behavior:"smooth"})}}><input aria-label="Search movies" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles, genres, movie night..." /><button className="primary" type="submit">Explore ↗</button></form></div><div className="hero-art" aria-hidden="true"><div className="orb"/><div className="float-card float-one"><strong>✦ A better kind of discovery</strong><small>Movies matched to your mood</small></div><div className="float-card float-two"><div className="float-stars">★★★★★</div><strong>Stories worth staying up for</strong><small>24 films to explore · growing soon</small></div></div></section>
 <TMDBCollection />
 <section className="shell" id="discover"><div className="section-head"><div><div className="eyebrow">THE COLLECTION</div><h2>{view==="For You"?"Made for your taste":view==="Top Rated"?"The audience favourites":view==="Watchlist"?"Your watchlist":"Find your next favourite"}</h2><p>{activeLabel}</p></div><div style={{color:"#a6adbb",fontSize:12}}>{movies.length} films <span style={{color:"#c5ff4a"}}>✦</span></div></div><div className="filters">{(["Discover","Top Rated","For You","Watchlist"] as View[]).map(v=><button key={v} className={"chip "+(view===v?"active":"")} onClick={()=>setView(v)}>{v==="For You"?"✦ For You":v==="Watchlist"?"♡ Watchlist":v}</button>)}<span style={{width:1,background:"#303541",margin:"3px 5px"}}/>{GENRES.map(g=><button key={g} className={"chip "+(genre===g?"active":"")} onClick={()=>setGenre(g)}>{g}</button>)}</div><div className="movie-grid">{movies.map(m=><article className="movie-card" key={m.id} onClick={()=>openMovie(m)}><div className="poster" style={{background:m.palette}}>{posters[m.id] ? <img className="curated-poster-image" src={`https://image.tmdb.org/t/p/w500${posters[m.id]}`} alt={`${m.title} poster`} loading="lazy" onError={e=>{e.currentTarget.style.display="none";}} /> : <div className="poster-symbol">{m.symbol}</div>}<div className="poster-copy"><div className="poster-kicker">CINESPHERE · {m.year}</div><div className="poster-title">{m.title}</div></div></div><div className="movie-info"><div className="movie-title">{m.title}</div><div className="movie-meta"><span>{m.year} · {m.genres[0]}</span><span className="rating">★ {m.rating.toFixed(1)}</span></div><span className="tag">{watchlist.includes(m.id)?"♥ Saved":"＋ View details"}</span></div></article>)}{movies.length===0&&<div className="empty">No films found. Try another title or genre.</div>}</div></section>
 <footer className="shell bottom"><div className="brand" style={{fontSize:15}}><div className="brand-mark" style={{width:25,height:25,borderRadius:8,fontSize:13}}>▶</div>Cine<span>Sphere</span></div><div>Made for movie lovers. Your watchlist stays on this device.</div><div>© {new Date().getFullYear()} CineSphere AI</div></footer>
 {selected&&<div className="detail-backdrop" onClick={()=>setSelected(null)}><section className="detail" onClick={e=>e.stopPropagation()}><div className="detail-top"><div className="detail-poster" style={{background:selected.palette,overflow:"hidden",position:"relative"}}>{posters[selected.id] ? <img src={`https://image.tmdb.org/t/p/w500${posters[selected.id]}`} alt={`${selected.title} poster`} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}} onError={e=>{e.currentTarget.style.display="none";}} /> : selected.symbol}</div><div><button className="close" style={{float:"right"}} aria-label="Close details" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">MOVIE SPOTLIGHT</div><h2>{selected.title}</h2><div style={{fontSize:12,color:"#aab0bd"}}>{selected.year}　<span className="rating">★ {selected.rating.toFixed(1)}</span></div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:12}}>{selected.genres.map(g=><span className="tag" key={g}>{g}</span>)}</div><p>{selected.synopsis}</p><div className="detail-actions"><button className="primary" onClick={()=>toggleWatch(selected.id)}>{watchlist.includes(selected.id)?"✓ In watchlist":"＋ Add to watchlist"}</button><a className="secondary" style={{textDecoration:"none",display:"inline-flex",alignItems:"center"}} target="_blank" rel="noreferrer" href={"https://www.imdb.com/find/?q="+encodeURIComponent(selected.title)}>Find on IMDb ↗</a></div></div></div><div className="detail-foot">Availability varies by region. External links help you find official listings; CineSphere does not host films.</div></section></div>}</main>;
}
